root: "LOG_PATH"
exp_name: "exp"
model: "tic_sfma"
dataset: "coco"
dataset_path: "data/coco2017"
fastrcnn_path: "./codec_ckpt/model_final_280758.pkl"
maskrcnn_path: "./codec_ckpt/model_final_f10217.pkl"
checkpoint: "codec_ckpt/base_codec_4.pth.tar"
epochs: 20
learning_rate: 1.e-4
milestones: [5, 10,15]
gpu: 0,1,2
gpu_id: 2
quality_level: 0.25 # {1,2,3,4}
task_lmbda: 0.25 # {0.5, 1, 2, 5}
num_workers: 16
batch_size: 16
test_batch_size: 1
aux_learning_rate: 1.e-3
patch_size: 256
cuda: True
save: True
clip_max_norm: 1.0
seed: 42

